#!/usr/bin/env python3
"""Generate a Rabbit project (.rbtprj) for a SeriWrap-generated wrapper.

Why this exists: Rabbit binds every component pin by hand, through a dropdown in
the component settings dialog.  A SeriWrap wrapper has dozens of them
(s_data_in[0..W-1], s_clk_in, s_strobe_in, s_data_out[0..W-1], s_clk_out,
s_data_valid, s_ready), so doing it by hand is tedious and easy to get wrong.

This tool reads the two files SeriWrap already produces
  * <top>__stream_manifest.json   -- word width, frame sizes, link mode
  * <top>_cons.xml                -- design port -> board pin
and writes a project that is fully bound, ready to open in Rabbit.

    python3 gen_rabbit_project.py --manifest mac13__stream_manifest.json \
        --cons mac13_cons.xml --out mac13.rbtprj [--bit mac13_bit.bit] \
        [--name mac13] [--component SeriWrap]
"""
import argparse
import json
import os
import sys
import xml.etree.ElementTree as ET


def read_cons(path):
    """design port name -> pin name"""
    root = ET.parse(path).getroot()
    return {p.get('name'): p.get('position') for p in root.findall('port')}


def binding(cons, design_port, logical_port, direction):
    """Emit one <input>/<output> element, or None when the port is absent."""
    pin = cons.get(design_port)
    if pin is None:
        return None
    tag = 'input' if direction == 'in' else 'output'
    return f'                <{tag} pin="{pin}" port="{logical_port}"/>'


def build(manifest_path, cons_path, name, component, bit):
    man = json.load(open(manifest_path))
    cons = read_cons(cons_path)
    width = int(man['link']['width'])
    has_ready = bool(man['frame']['handshake'].get('ready'))
    has_in = bool(man['frame'].get('has_input', man['frame']['input_words'] > 0))
    has_out = bool(man['frame'].get('has_output', man['frame']['output_words'] > 0))

    L = []
    L.append('<?xml version="1.0" encoding="UTF-8"?>')
    L.append('<!--Rabbit Project File (generated by SeriWrap tools/gen_rabbit_project.py)-->')
    attr = f'<project name="{name}" constraint="{os.path.basename(cons_path)}"'
    if bit:
        attr += f' bitstream="{os.path.basename(bit)}"'
    attr += ' waveform_enabled="false">'
    L.append(attr)
    L.append('    <panel grid_width="50" grid_height="50"/>')
    L.append('    <components>')

    ins, outs, missing = [], [], []

    if has_in:
        for k in range(width):
            e = binding(cons, f's_data_in[{k}]', f'DATA[{k}]', 'in')
            if e:
                ins.append(e)
            else:
                missing.append(f's_data_in[{k}]')
        for design, logical in (('s_clk_in', 'CLK'), ('s_strobe_in', 'STROBE')):
            e = binding(cons, design, logical, 'in')
            if e:
                ins.append(e)
            else:
                missing.append(design)

    if has_out:
        for k in range(width):
            e = binding(cons, f's_data_out[{k}]', f'DOUT[{k}]', 'out')
            if e:
                outs.append(e)
            else:
                missing.append(f's_data_out[{k}]')
        for design, logical in (('s_clk_out', 'CLK_OUT'), ('s_data_valid', 'DATA_VALID')):
            e = binding(cons, design, logical, 'out')
            if e:
                outs.append(e)
            else:
                missing.append(design)
    if has_out and has_ready:
        e = binding(cons, 's_ready', 'READY', 'out')
        if e:
            outs.append(e)
        else:
            missing.append('s_ready')

    L.append(f'        <component type="{component}" name="{component}" grid_x="8" grid_y="3">')
    L.append('            <settings>')
    L.append('                <setting name="hold_frames" value="20"/>')
    L.append('                <setting name="is_low_active" value="false"/>')
    L.append('            </settings>')
    L.append('            <inputs>')
    L.extend(ins if ins else ['            </inputs>'])
    if ins:
        L.append('            </inputs>')
    L.append('            <outputs>')
    L.extend(outs if outs else ['            </outputs>'])
    if outs:
        L.append('            </outputs>')
    L.append('        </component>')

    rst_pin = cons.get('rst_n')
    if rst_pin:
        L.append('        <component type="Switch" name="rst" grid_x="0" grid_y="0">')
        L.append('            <settings>')
        L.append('                <setting name="is_low_active" value="true"/>')
        L.append('            </settings>')
        L.append('            <inputs>')
        L.append(f'                <input pin="{rst_pin}" port="SW"/>')
        L.append('            </inputs>')
        L.append('            <outputs/>')
        L.append('        </component>')

    L.append('    </components>')
    L.append('</project>')
    return '\n'.join(L) + '\n', missing


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--manifest', required=True)
    ap.add_argument('--cons', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--name', default=None)
    ap.add_argument('--component', default='SeriWrap')
    ap.add_argument('--bit', default=None)
    args = ap.parse_args()

    name = args.name or os.path.basename(args.manifest).split('__')[0]
    text, missing = build(args.manifest, args.cons, name, args.component, args.bit)
    with open(args.out, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print(f'{args.out}: bound {text.count("<input ")} inputs and {text.count("<output ")} outputs')
    if missing:
        print(f'  WARNING: {len(missing)} design ports were not in the constraint file: '
              + ', '.join(missing[:8]) + (' ...' if len(missing) > 8 else ''))
    return 0 if not missing else 0


if __name__ == '__main__':
    sys.exit(main())
